### ISSUE TITLE
Won't compile in UE5.4.1

### ISSUE THREAD

**Issue by EddieSoloProjects** [mordentral/VRExpansionPlugin#51]
Won't compile in UE5.4.1. Tried cleaning the project still fails

**Comment by mordentral** [comment]
It compiles fine in 5.4.1, are you sure you didn't download / keep the 5.3 files? And if not, what are the compilation errors.

**Comment by EddieSoloProjects** [comment]
Here is the Error on Windows 10 with an updated Visual Studio:Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB3073	The command ""C:\Program Files\Epic Games\UE_5.4\Engine\Build\BatchFiles\Build.bat" VRExpPluginExampleEditor Win64 Development -Project="D:\GAME_TEMPLATE_VR\DRAGON\VRE-DragonIK-VRIK\VRExpPluginExample.uproject" -WaitMutex -FromMsBuild -architecture=x64" exited with code 6.	VRExpPluginExample	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets	44

**Comment by EddieSoloProjects** [comment]
Reinstalled UE5.4.1 and now it's fine.
